# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Caravan' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Caravan

# add the Firebase pod for Google Analytics
pod 'Firebase/Analytics'
pod 'Firebase/Auth'
# add pods for any other desired Firebase products
pod 'Firebase/Core'
pod 'Firebase/Firestore'
pod 'Firebase/Database'
pod 'Firebase/Storage'
pod 'MessageKit'
# https://firebase.google.com/docs/ios/setup#available-pods

end
